/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Companylogo: typeof import('./components/Companylogo.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    OverhiringChart: typeof import('./components/OverhiringChart.vue')['default']
    QuarterlyChart: typeof import('./components/QuarterlyChart.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./components/Upload.vue')['default']
    User: typeof import('./components/User.vue')['default']
  }
}
